name: Pages Build and Deploy
on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  build-and-deploy:
    name: generate and deploy
    strategy:
      matrix:
        conference: [heapcon25, gotechworld25, 040codersignite25, ndcmanchester25]
      max-parallel: 1  # Ensure jobs run sequentially to avoid GitHub Pages conflicts
    
    concurrency: ci-${{ github.ref }}-${{ matrix.conference }} # Recommended if you intend to make multiple deployments in quick succession.
    permissions:
      contents: write # requires to push generated slides
    
    runs-on: ubuntu-latest
    env:
      CONFERENCE: ${{ matrix.conference }}
    
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: ğŸ”§ Install
        run: |
          npm ci
          
      - name: ğŸ”§ Build pages for ${{ matrix.conference }}
        run: |
          npm run build-html

      - name: ğŸš€ Deploy ${{ matrix.conference }}
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
        with:
          branch: gh-pages
          folder: build-${{ matrix.conference }}
          target-folder: ${{ matrix.conference }}
